source 'https://rubygems.org'

gem 'google-apis-calendar_v3', '~> 0.1'
gem 'google-apis-drive_v3', '~> 0.1'

gem 'google-id-token', '~> 1.3'
gem 'redis', '>= 3.2', '< 5.0.7'
gem 'dotenv'
gem 'sinatra'
gem 'mime-types-data'
gem 'webrick'
