include:
  - name: appsmarket
    version: v2
    discovery_rest_url: https://content.googleapis.com/discovery/v1/apis/appsmarket/v2/rest
  - name: youtubePartner
    version: v1
    discovery_rest_url: https://content.googleapis.com/discovery/v1/apis/youtubePartner/v1/rest
exclude:
  # 📝 Exclusions logged and tracked by b/542740217
  - discoveryengine.v1
  - discoveryengine.v1alpha
pause: []
