name: Generate-Updates
on:
  schedule:
    - cron: '02 11 * * *'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/google-api-ruby-client' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install tools
        run: "gem install --no-document toys"
      - name: execute
        run: |
          toys generate-updates -v --fork ${{ github.event.inputs.args }}
