name: Unfreeze releases

permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/google-api-ruby-client' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Install Ruby 4.0
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: "4.0"
      - name: Install tools
        run: |
          gem install --no-document toys
      - name: execute
        run: |
          toys freeze-releases -v --fork --off
